name: Alex Reid
author: Alex Reid
baseurl: /herring-cove
description: theme for jekyll
github: http://www.github.com/arnp
##twitter: http://www.twitter.com/
##facebook: http://www.facebook.com
linkedin: https://www.linkedin.com/in/alex-reid-5263a3168/
email: rnpatel[at]me.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
